-- ===========================================================================
-- Aurora PostgreSQL — e-commerce OLTP source schema (requirement 3).
--
-- CDC prerequisites for DMS on Aurora PostgreSQL:
--   * rds.logical_replication = 1 (cluster parameter group) -> wal_level=logical
--   * A DMS user with REPLICATION + SELECT on the tables.
--   * Primary keys on every table so UPDATE/DELETE CDC carries the key.
-- ===========================================================================

CREATE SCHEMA IF NOT EXISTS public;

-- customers -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
    customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL,
    email         TEXT        NOT NULL UNIQUE,
    city          TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- products ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    product_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL,
    category      TEXT,
    price         NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- orders --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    order_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT      NOT NULL REFERENCES customers(customer_id),
    order_date    TIMESTAMPTZ NOT NULL DEFAULT now(),
    order_amount  NUMERIC(12,2) NOT NULL CHECK (order_amount >= 0),
    status        TEXT        NOT NULL
                    CHECK (status IN ('PLACED','SHIPPED','DELIVERED','CANCELLED')),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);

-- order_items ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT      NOT NULL REFERENCES orders(order_id),
    product_id    BIGINT      NOT NULL REFERENCES products(product_id),
    quantity      INTEGER     NOT NULL CHECK (quantity >= 0),
    unit_price    NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_items_order ON order_items(order_id);

-- payments ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
    payment_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT      NOT NULL REFERENCES orders(order_id),
    amount        NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    status        TEXT        NOT NULL
                    CHECK (status IN ('PENDING','COMPLETED','FAILED','REFUNDED')),
    paid_at       TIMESTAMPTZ,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_payments_order ON payments(order_id);

-- Keep updated_at fresh on UPDATE so ordering/watermarks are meaningful.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['customers','products','orders','order_items','payments'] LOOP
        EXECUTE format(
          'DROP TRIGGER IF EXISTS trg_%1$s_updated ON %1$s;
           CREATE TRIGGER trg_%1$s_updated BEFORE UPDATE ON %1$s
           FOR EACH ROW EXECUTE FUNCTION set_updated_at();', t);
    END LOOP;
END $$;

-- REPLICA IDENTITY FULL makes DELETE/UPDATE CDC carry full "before" images,
-- which improves downstream diagnostics and lets DMS emit complete keys.
ALTER TABLE customers   REPLICA IDENTITY FULL;
ALTER TABLE products    REPLICA IDENTITY FULL;
ALTER TABLE orders      REPLICA IDENTITY FULL;
ALTER TABLE order_items REPLICA IDENTITY FULL;
ALTER TABLE payments    REPLICA IDENTITY FULL;
